// APP
CANVAS_WIDTH = 512;
CANVAS_HEIGHT = 480;
DEBUG_ENABLED = true;

// HUD
SCORE_FILL_STYLE = "rgb(250, 250, 250)";
SCORE_FONT = "24px Helvetica";

// PLAYER
PLAYER_NAME = "HA!";
PLAYER_PB = 0;

// GAME STATE
HERO_BASE_SPEED = 256;