// APP
CANVAS_WIDTH = 512;
CANVAS_HEIGHT = 480;
DEBUG_ENABLED = false;

// HUD
SCORE_FILL_STYLE = "rgb(250, 250, 250)";
SCORE_FONT = "24px Helvetica";

// PLAYER
PLAYER_NAME = "HA!";
PLAYER_PB = 0;

// GAME STATE
HERO_BASE_SPEED = 256;
HERO_WIDTH = 32;
HERO_HEIGHT = 32;

MONSTER_WIDTH = 32;
MONSTER_HEIGHT = 32;